[package]
name = "pod5-format"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
flatbuffers = "24.3.25"
thiserror.workspace = true

[dev-dependencies]
eyre.workspace = true