[workspace]
members = [
    "examples/arrow-example",
    "examples/convert-to-slow5",
    "examples/find-all-reads",
    "pod5frame-py",
]

[workspace.package]
authors = ["Brandon Saint-Joh <saint-john@lbl.gov>"]

[package]
name = "pod5"
version = "0.1.0"
edition = "2021"
authors.workspace = true
description = "Interacting with POD5 files in Rust."
readme = "README.md"
repository = "https:://github.com/bsaintjo/pod5-rs"
license = "MIT OR Apache-2.0"
keywords = ["nanopore", "genomics", "FAST5", "POD5", "sequencing"]
categories = [
    "science",
    "parsing",
    "data-structures",
    "compression",
    "encoding",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# encode/decode of sizes in control bytes in svb
bitvec = "1.0.1"
delta-encoding = "0.4.2"
zigzag = "0.1.0"
zstd = "0.13.3"

# chunking control bytes during decoding
itertools = "0.14.0"

# Parsing footer schema
flatbuffers = "24.3.25"

# Error handling
thiserror = "2.0.11"

# DataFrame API
polars-arrow = { version = "0.46.0", features = ["io_ipc"] }
polars = { version = "0.46.0", features = [
    "dtype-full",
    "dtype-array",
    "timezones",
    "lazy",
    "list_arithmetic"
] }

# Parsing read ids
uuid = { version = "1.14.0", features = ["v4"] }
log = "0.4.25"
arrow = "54.2.0"
lru = "0.13.0"
polars-schema = "0.46.0"


[dev-dependencies]
doc-comment = "0.3.3"
env_logger = "0.11.8"
eyre = "0.6.8"
# Testing small files by memmap
memmap2 = "0.9.5"
pretty_assertions = "1.4.1"
proptest = "1.6.0"
