[package]
name = "pod5-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Parse embedded arrow files and data types
arrow2 = { version = "0.16.0", features = ["io_ipc"] }
arrow2_convert = "0.4.2"

# encode/decode of sizes in control bytes in svb
bitvec = "1.0.1"
delta-encoding = "0.4.0"
zigzag = "0.1.0"
zstd = "0.12.3"

# chunking control bytes during decoding
itertools = "0.10.5"

# Parsing footer schema
flatbuffers = "23.1.21"

# Error handling
eyre = "0.6.8"
miette = "5.5.0"
thiserror = "1.0.39"
polars-arrow = { version = "0.37.0", features = ["io_ipc", "compute_cast"] }
polars = { version = "0.37.0", features = ["dtype-full", "dtype-array"] }


[dev-dependencies]
# Testing small files by memmap
memmap2 = "0.5.10"
