[package]
name = "convert-to-slow5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pod5 = { path = "../..", version = "0.1"}
slow5 = "0.11.0"
