[package]
name = "pod5frame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pod5frame"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.0"
pod5 = { path = ".." }
pyo3-polars = "0.20.0"
