[package]
name = "arrow-example"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[dependencies]
arrow = "53.3.0"
eyre = "0.6.12"
pod5 = { path = "../..", version = "0.1"}
uuid = "1.11.0"
