[package]
name = "find-all-reads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.12"
pico-args = "0.5.0"
pod5 = { path = "../..", version = "0.1"}
